[package]
name = "helixdb"
version = "0.1.0"
authors = ["Ruihang Xia <waynestxia@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
protos = { path = "protos" }
flatbuffers = "0.7.0"
io-uring = "0.5.0"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
tempfile = "3.2"
